version: '3.8'

services:
  api:
    build: .
    ports:
      - "4000:8000"
    volumes:
      - ./:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]